### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by 9Mad-Max5** [crack00r/Flexget-Config#19]
Ich habe sowohl python 3 als auch 2 jeweils mit dem selben Fehler an dieser Stelle.
Ist es möglicherweise ein Problem beim anlegen des trakt Username.

`Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task_queue.py", line 48, in run
    self.current_task.execute()
  File "c:\python27\lib\site-packages\flexget\task.py", line 80, in wrapper
    return func(self, *args, **kw)
  File "c:\python27\lib\site-packages\flexget\task.py", line 693, in execute
    self._execute()
  File "c:\python27\lib\site-packages\flexget\task.py", line 659, in _execute
    self.__run_task_phase(phase)
  File "c:\python27\lib\site-packages\flexget\task.py", line 492, in __run_task_phase
    for e in response:
  File "c:\python27\lib\site-packages\flexget\utils\cached_input.py", line 201, in __iter__
    for item in self.iterable:
  File "c:\python27\lib\site-packages\flexget\components\trakt\trakt_list.py", line 305, in get_items
    raise plugin.PluginError('Could not retrieve list from trakt (%s)' % e)
PluginError: Could not retrieve list from trakt (404 Client Error: Not Found for url: https://api.trakt.tv/users/USERNAME/lists/listname/items?limit=1000&page=1)
`

**Comment by snickers2k** [comment]
fixed (?)

**Comment by 9Mad-Max5** [comment]
Der Fehler kommt immer noch im crashreport.
Allerdings ist auch noch folgendes zu finden:

`2019-09-01 15:33 CRITICAL template      Movies_Watchlist_Stream_Main Unable to find template {? enable_disable.Upgrade_Movies ?}-Upgrade-Movies for task Movies_Watchlist_Stream_Main
2019-09-01 15:33 WARNING  task          Movies_Watchlist_Stream_Main Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Movies_Watchlist_Stream_Low Unable to find template {? enable_disable.Upgrade_Movies ?}-Upgrade-Movies for task Movies_Watchlist_Stream_Low
2019-09-01 15:33 WARNING  task          Movies_Watchlist_Stream_Low Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Movies_Watchlist_Stream_4K Unable to find template {? enable_disable.Upgrade_Movies ?}-Upgrade-Movies for task Movies_Watchlist_Stream_4K
2019-09-01 15:33 WARNING  task          Movies_Watchlist_Stream_4K Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Series_Collection_DE_Seasons Unable to find template {? enable_disable.OnHold ?}-OnHold for task Series_Collection_DE_Seasons
2019-09-01 15:33 WARNING  task          Series_Collection_DE_Seasons Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Series_Collection_DE_Stream Unable to find template {? enable_disable.OnHold ?}-OnHold for task Series_Collection_DE_Stream
2019-09-01 15:33 WARNING  task          Series_Collection_DE_Stream Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Series_Watchlist Unable to find template {? enable_disable.Canceled ?}-Canceled for task Series_Watchlist
2019-09-01 15:33 WARNING  task          Series_Watchlist Aborting task (plugin: template)
2019-09-01 15:33 INFO     interval      Merge_Trakt_Lists No previous run recorded, running now
2019-09-01 15:33 VERBOSE  trakt_list    Merge_Trakt_Lists Retrieving `movies` list `LISTNAME`
2019-09-01 15:33 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
2019-09-01 15:33 CRITICAL manager                       An unexpected crash has occurred. Writing crash report to /home/piloader/.flexget/crash_report.2019.09.01.153337904791.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.21.17
2019-09-01 15:33 VERBOSE  interval      Movies_Watchlist_Search_DE_Main Interval 24 hours not met on task Movies_Watchlist_Search_DE_Main. Use --now to override.
2019-09-01 15:33 CRITICAL template      Sync_Movies_Popular Unable to find template {? enable_disable.Download_Popular_Movies ?}-Download_Popular_Movies for task Sync_Movies_Popular
2019-09-01 15:33 WARNING  task          Sync_Movies_Popular Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Sync_Movies_Trending Unable to find template {? enable_disable.Download_Trending_Movies ?}-Download_Trending_Movies for task Sync_Movies_Trending
2019-09-01 15:33 WARNING  task          Sync_Movies_Trending Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Series_Collection_DE_Search Unable to find template {? enable_disable.OnHold ?}-OnHold for task Series_Collection_DE_Search
2019-09-01 15:33 WARNING  task          Series_Collection_DE_Search Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Sync_Actors_Movies Unable to find template {? enable_disable.Actors ?}-Actors for task Sync_Actors_Movies
2019-09-01 15:33 WARNING  task          Sync_Actors_Movies Aborting task (plugin: template)
2019-09-01 15:33 VERBOSE  interval      Movies_Watchlist_Search_DE_Low Interval 24 hours not met on task Movies_Watchlist_Search_DE_Low. Use --now to override.
2019-09-01 15:33 CRITICAL template      Sports          Unable to find template {? enable_disable.Download_Sports ?}-Download_Sports for task Sports
2019-09-01 15:33 WARNING  task          Sports          Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Specials        Unable to find template {? enable_disable.Download_Specials ?}-Download_Specials for task Specials
2019-09-01 15:33 WARNING  task          Specials        Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      move-Series     Unable to find template {? enable_disable.Sorting ?}-Sorting for task move-Series
2019-09-01 15:33 WARNING  task          move-Series     Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Specials2       Unable to find template {? enable_disable.Download_Specials2 ?}-Download_Specials2 for task Specials2
2019-09-01 15:33 WARNING  task          Specials2       Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      YouTube-Personal-Playlist Unable to find template {? enable_disable.YouTube_Downloads ?}-YouTube_Downloads for task YouTube-Personal-Playlist
2019-09-01 15:33 WARNING  task          YouTube-Personal-Playlist Aborting task (plugin: template)
2019-09-01 15:33 CRITICAL template      Comedy_Shows    Unable to find template {? enable_disable.Download_Sports ?}-Download_Sports for task Comedy_Shows
2019-09-01 15:33 WARNING  task          Comedy_Shows    Aborting task (plugin: template)
`

**Comment by 9Mad-Max5** [comment]
Jop fixed wie topy gesagt hat lag es an der übergabe der varaiblen.
